hoelzer-lab/rnaflow

main.nf
modules/annotationGet.nf
modules/hisat2.nf
modules/prepare_annotation.nf
modules/referenceGet.nf
nextflow.config

some changes for usage with Virus SSP data

Adapt to vssp

---

README.md
envs/sortmerna.yaml
main.nf
modules/annotationGet.nf
modules/deseq2.nf
modules/fastp.nf
modules/featurecounts.nf
modules/hisat2.nf
modules/multiqc.nf
modules/prepare_annotation.nf
modules/referenceGet.nf
modules/sortmerna.nf
modules/sortmernaGet.nf
modules/tpm_filter.nf
nextflow.config

- solved #31, #32, #33
- works with compressed files (fastp, SMR)

Newfeatures

---

envs/multiqc.yaml
nextflow.config

fixed multiqc install (only -c conda-forge missing)
changed workdir to $USER specific version

minor changes (install multiqc and workdir)

---

configs/slurm.config
modules/annotationGet.nf
modules/deseq2.nf
modules/hisat2.nf
modules/multiqc.nf
modules/prepare_annotation.nf
modules/referenceGet.nf
modules/sortmernaGet.nf
modules/tpm_filter.nf
nextflow.config

edits in ARA profile:
- local execution  for some processes
- retries for HISAT2 (fixes #44 )
- parameters for non-local  execution

Hpc tweaks

---

scripts/deseq2.R

add simple version of deseq2 comparison

---

scripts/csv_to_excel.py

the conda env needs also openpyxl

convert csv to xlsx

---

bin/deseq2.R
bin/refactor_reportingtools_table.rb

This fixes #38 for now. 
But we need to think about a better way to work with the ReportingTools package (I will open an extra issue)

hack to fix #38

---

assets/multiqc_config.yaml
main.nf
modules/fastp.nf
modules/fastqc.nf
modules/multiqc.nf
modules/tpm_filter.nf
nextflow.config

- `FastQC` before and after `fastp`
- additional parameter for `fastp`
- sample renaming in MultiQC report (#16)

Quality control

---

main.nf
nextflow.config

added skip SMR option

---

envs/subread.yaml
main.nf
modules/featurecounts.nf
modules/tpm_filter.nf

* updated subread version
* fixed #63 by adding .tsv suffix
* adjusted channel filtering for TPM step so that samples get not mixed anymore

Update channel logic to keep correct order for TPM filter step

---

bin/deseq2.R
envs/deseq2.yaml

- for pairwise comparisons
- solves #83

added volcano plots

---

bin/deseq2.R
main.nf

Marie lataretu/issue109

---

modules/annotationGet.nf
modules/referenceGet.nf

cat * > foo.bar does not work in cloud

---

README.md
main.nf
nextflow.config

- removed params.workdir
- added note in help message

removed params.workdir Fixes #112

---

main.nf
nextflow.config

Let's see if this works now for https://github.com/hoelzer-lab/rnaflow/issues/136 and then should be safe to merge and do a new release

nextflow version check to fix #136

---

README.md

Add information on screen/tmux usage to README

---

README.md
main.nf
modules/rattle.nf
nextflow.config

- added new pipeline parameter `--rna` to activate directRNA mode for ONT transcriptome assembly with `rattle`
- added documentation for `--rna` in help message and `README`
- fixed a typo in README
- updated busco DB lineage (v5) overview link in help message and `README`

new parameter --rna, closes #163

---

README.md
bin/deseq2.R

Flip the fold change also for the (html) report (related to #156 )

Fc flip report

---

configs/conda.config
main.nf
modules/containerGet.nf

Added support for setup mode with conda profiles and the new mamba engine support!

Setup mode support for conda and mamba

---

README.md

update DGE result documentation (explanation) to be more precise and more clear for users

update DGE result documentation

---

nextflow.config

wip and needs confirmation from #232

add pbspro executor

---

README.md
configs/container.config
envs/hisat2.yaml
modules/hisat2.nf

Fix tmp dir location for HISAT2

---

envs/fastp.yaml
envs/hisat2.yaml
envs/minimap2.yaml
envs/multiqc.yaml
envs/nanoplot.yaml
envs/sortmerna.yaml
envs/stringtie.yaml
envs/subread.yaml
envs/trinity.yaml
modules/hisat2.nf
modules/sortmerna.nf
modules/sortmernaGet.nf

Bump conda version for sortmerna to match container. Also add conda-forge channel to conda envs when missing. Finally, add a parameter to sortmerna to write output on the process work dir and not the user home

Smr conda version bump & path fix
